title: JEONHA
description: 흩어진 생각을 다스리는 곳
author: "Jusang"

theme: minima

base_url: ""
repository: aijusang/aijusang.github.io
# Minima social links
github_username: aijusang
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
